version: "3.1"

networks:
  proxy-net:
    external:
      name: proxy-net

services:
  match-maker:
    container_name: match-maker
    networks:
      - proxy-net
    build: .
    restart: always
    environment:
      - VIRTUAL_HOST=match-maker.viktor-braun.de
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=match-maker.viktor-braun.de
      - LETSENCRYPT_EMAIL=mail@viktor-braun.de
